const ERROR = {
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  AUTHORISATION_ERROR: 'AUTHORISATION_ERROR',
};

const COLLECTION = {};

module.exports = {
  ERROR,
  COLLECTION,
};
